### ISSUE TITLE
Contagem de pontuação e contagem de rodadas

### ISSUE THREAD

**Issue by rafMewtwo** [leocostarj22/GameMemoryStrangerThings#1]
Salve Leo,  sou desenvolvedor também curti pakas o que vc fez p/ sua filha...
Fiz uma att p/ fazer uma contagem de pontos e contar quantas rodadas a pessoa levou p/ acabar o game...
Tentei fazer um PR mas deu permissao negada, entao vou mandar as funcoes por aqui e vc add no codigo blz?

No arquivo script vc add isso

let points = 0;
let turns = 0;

function updatePoints() {
  currentPoints = document.getElementById('points');
  points++;
  currentPoints.innerHTML = points;
}

function updateTurns() {
  currentTurns = document.getElementById('turns');
  turns++;
  currentTurns.innerHTML = turns;
}

vc vai chamar a updateTurns no final da func flipCard

e a updatePoints dentro do if  da funcao checkForMatch

no html vc add essa div entre o body e o main

<div class="board">
        <div class="boardPoints">
          <h3 class="title">Points : </h3><h3 class="title"  id="points">0</h3>
        </div>
        <div class="boardPoints">
          <h3 class="title">Jogadas : </h3><h3 class="title" id="turns">0</h3>
        </div>
      </div>

dps soh add no css dos 2 games

.title {
    color: #FFF;
}

.board {
    position: absolute;
    margin-left: 30px;
    margin-top: 30px;
}

.boardPoints {
    display: flex;
}

é claro se fizer sentido p/ vc também essas alteracoes
qlqr coisa da um toque, boa iniciativa!

**Comment by leocostarj22** [comment]
Top demais! Obrigado meu amigo!!!

**Comment by leocostarj22** [comment]
Atualizado! Funcionou! Tmj!
